ci: retry test suite on failure

diff --git a/.github/workflows/e2e-android.yml b/.github/workflows/e2e-android.yml
--- a/.github/workflows/e2e-android.yml
+++ b/.github/workflows/e2e-android.yml
@@ -139,6 +139,35 @@ jobs:
               exit 1
             fi
 
+      - name: Prepare test script file
+        id: e2e-test-script
+        run: |
+          # android-emulator-runner does not support multi-line scripts
+          # so we create a script file and pass its path instead
+
+          SCRIPT_FILE="$(pwd)/e2e-tests.sh"
+
+          echo "${SCRIPT}" > "${SCRIPT_FILE}"
+          echo "file=${SCRIPT_FILE}" >> "${GITHUB_OUTPUT}"
+        env:
+          SCRIPT: |
+            adb install ../android-debug-build/android-debug.apk
+
+            for i in 1 2 3; do
+              yarn run e2e:native --flatten-debug-output
+
+              if [ $? -eq 0 ]; then
+                break
+              else
+                echo "Maestro tests failed on attempt $i"
+
+                if [ $i -eq 3 ]; then
+                  echo "Maestro tests failed after $i attempts"
+                  exit 1
+                fi
+              fi
+            done
+
       - name: Run Maestro tests
         uses: reactivecircus/android-emulator-runner@v2
         with:
@@ -149,12 +178,10 @@ jobs:
           emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none
           avd-name: ${{ env.AVD_NAME }}
           arch: x86_64
-          script: |
-            adb install ../android-debug-build/android-debug.apk
-            yarn run e2e:native
+          script: bash ${{ steps.e2e-test-script.outputs.file }}
           working-directory: example
         env:
-          MAESTRO_DRIVER_STARTUP_TIMEOUT: 120000
+          MAESTRO_DRIVER_STARTUP_TIMEOUT: 240000
 
       - name: Store debug output if failed
         if: failure()
diff --git a/.github/workflows/e2e-ios.yml b/.github/workflows/e2e-ios.yml
--- a/.github/workflows/e2e-ios.yml
+++ b/.github/workflows/e2e-ios.yml
@@ -104,6 +104,7 @@ jobs:
             fi
 
             STATUS=$(xcrun simctl list | grep "$DEVICE_ID" | grep "(Booted)")
+
             if [[ -n "$STATUS" ]]; then
               echo "Simulator is booted!"
               break
@@ -131,7 +132,21 @@ jobs:
       - name: Run Maestro tests
         run: |
           xcrun simctl install booted ../ios-debug-build/ios-debug.app
-          yarn run e2e:native
+
+          for i in 1 2 3; do
+            yarn run e2e:native --flatten-debug-output
+
+            if [ $? -eq 0 ]; then
+              break
+            else
+              echo "Maestro tests failed on attempt $i"
+
+              if [ $i -eq 3 ]; then
+                echo "Maestro tests failed after $i attempts"
+                exit 1
+              fi
+            fi
+          done
         env:
           MAESTRO_DRIVER_STARTUP_TIMEOUT: 240000
         working-directory: example
